/**
 * Beschreibung je Wert-ID — jeweils die Klausel NACH "Dir ist wichtig, dass "
 * (die Seite setzt den Satz daraus zusammen). Custom-Werte und Legacy-IDs
 * bekommen die Default-Klausel.
 */
export const VALUE_DESCRIPTIONS: Record<string, string> = {
  authenticity: "du du selbst sein kannst — ohne Maske und ohne Verstellung",
  "self-compassion": "du dir selbst mit der gleichen Güte begegnest wie einem guten Freund",
  honesty: "du ehrlich bist, auch wenn es unbequem ist",
  integrity: "dein Handeln mit deinen Überzeugungen übereinstimmt",
  mindfulness: "du präsent im Moment bist, statt im Autopilot zu leben",
  courage: "du dich traust, auch wenn die Angst mitredet",
  assertiveness: "du für dich einstehst und deine Grenzen klar machst",
  resilience: "du nach Rückschlägen wieder aufstehst",
  empowerment: "du deine eigene Kraft spürst und Entscheidungen selbst triffst",
  "self-discipline": "du dranbleibst, auch wenn die Motivation nachlässt",
  responsibility: "du Verantwortung für dein Handeln übernimmst",
  growth: "du dich weiterentwickelst und über dich hinauswächst",
  curiosity: "du Neues entdeckst und Fragen stellst",
  creativity: "du deine Ideen Gestalt annehmen lässt",
  wisdom: "du innehältst und aus Erfahrung lernst",
  empathy: "du dich in andere hineinfühlen kannst",
  kindness: "du anderen mit Freundlichkeit begegnest",
  generosity: "du gibst, ohne sofort etwas zurückzuerwarten",
  connection: "du echte Nähe zu anderen Menschen lebst",
  service: "du etwas beiträgst, das über dich hinausreicht",
  gratitude: "du das Gute in deinem Leben wahrnimmst und wertschätzt",
  forgiveness: "du loslässt, was dich belastet — bei anderen und bei dir",
  balance: "du Arbeit, Ruhe und Leben in Einklang bringst",
  rest: "du dir Pausen gönnst, ohne ein schlechtes Gewissen",
  "physical-health": "du gut für deinen Körper sorgst",
  joy: "du dir Momente der Freude erlaubst",
  humor: "du das Leben auch leicht nehmen kannst",
  purpose: "dein Tun einen Sinn hat, der dich trägt",
  adventurousness: "du dich auf Neues und Unbekanntes einlässt",
  "letting-go": "du loslassen kannst, was du nicht kontrollieren kannst",
  "quality-relationships": "deine Beziehungen Tiefe haben, statt bloß Kontakte zu sein",
  "time-management": "du deine Zeit bewusst einteilst, statt sie verrinnen zu lassen",
  optimism: "du auch im Schwierigen noch das Mögliche siehst",
  patience: "du den Dingen die Zeit gibst, die sie brauchen",
  intention: "du bewusst handelst, statt aus Gewohnheit",
  appreciation: "du siehst und aussprichst, was andere beitragen",
  diligence: "du Dinge sorgfältig zu Ende bringst",
  harmony: "es zwischen dir und den Menschen um dich stimmig bleibt",
  celebration: "du innehältst und feierst, was gelungen ist",
  "open-mindedness": "du andere Sichtweisen zulässt, bevor du urteilst",
  passion: "dich das, was du tust, wirklich brennen lässt",
  enthusiasm: "du dich für Dinge begeistern kannst",
  learning: "du dazulernst und dabei nie ganz fertig wirst",
  positivity: "du eine gute Grundstimmung in den Tag trägst",
  community: "du Teil von etwas bist, das größer ist als du",
  advocacy: "du deine Stimme für andere erhebst",
  accountability: "du zu deinen Zusagen stehst, auch wenn niemand nachfragt",
  excellence: "du Dinge richtig gut machst, nicht nur fertig",
  innovation: "du neue Wege ausprobierst, statt beim Bewährten zu bleiben",
  benevolence: "du anderen das Beste wünschst, ohne etwas davon zu haben",
  simplicity: "dein Leben leicht und unkompliziert bleibt",
  "real-connection": "du dich wirklich zeigst, statt an der Oberfläche zu bleiben",
  solitude: "du Zeit für dich allein hast und sie dir nimmst",
  fitness: "du in Bewegung bleibst und deinen Körper forderst",
  "growth-mindset": "du Können für erlernbar hältst, nicht für angeboren",
  quality: "du lieber weniger machst, das dafür richtig",
  environmentalism: "du achtsam mit der Natur umgehst",
  "hard-work": "du dranbleibst und die Arbeit wirklich machst",
  bravery: "du auch dann standhältst, wenn es unbequem wird",
  "mindful-speech": "du deine Worte wählst, bevor du sie sagst",
  commitment: "du hältst, was du zusagst",
  education: "du dir Wissen aneignest und es weitergibst",
  philanthropy: "du teilst, was du hast, mit denen, die weniger haben",
  boldness: "du groß denkst und den ersten Schritt trotzdem machst",
  altruism: "du an andere denkst, bevor du an dich denkst",
  minimalism: "du mit weniger auskommst und dich dadurch freier fühlst",
  inclusivity: "alle dazugehören dürfen, so wie sie sind",
  courteousness: "du anderen mit Respekt und Aufmerksamkeit begegnest",
  adaptability: "du dich neu einstellen kannst, wenn Pläne kippen",
  experiences: "du Erlebnisse sammelst statt Dinge",
  "work-life-balance": "Arbeit und Leben jeweils ihren eigenen Platz behalten",
  beauty: "du das Schöne wahrnimmst, im Großen wie im Kleinen",
  "open-expression": "du aussprichst, was in dir vorgeht, statt es zu schlucken",
  graciousness: "du freundlich bleibst, auch wenn du im Recht wärst",
  constructiveness: "du an Lösungen baust, statt beim Problem zu bleiben",
  pragmatism: "du das tust, was tatsächlich funktioniert",
  diversity: "unterschiedliche Menschen und Sichtweisen zusammenkommen",
  humility: "du dich nicht größer machst, als du bist",
  spirituality: "du dich mit etwas verbunden fühlst, das über dich hinausgeht",
  resourcefulness: "du aus dem, was da ist, etwas machst",
};

export const DEFAULT_VALUE_DESCRIPTION = "dieser Wert dein Handeln leitet";

export function getValueDescription(id: string): string {
  return VALUE_DESCRIPTIONS[id] ?? DEFAULT_VALUE_DESCRIPTION;
}
